#!/usr/bin/env ruby

require_relative "./lib/muzak"

git_tags = `git tag`.split("\n")

if git_tags.include?(Muzak::VERSION)
  puts "Did you forget to update Muzak::VERSION?"
  exit
end

system "git tag #{Muzak::VERSION}"
system "git push origin #{Muzak::VERSION}"
system "gem build muzak"
system "gem push muzak-#{Muzak::VERSION}.gem"

File.delete("muzak-#{Muzak::VERSION}.gem")
